# Generated by Django 6.0.4 on 2026-04-24 21:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_immatriculation', models.CharField(max_length=20, unique=True)),
                ('capacite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('marque', models.CharField(blank=True, max_length=50)),
                ('date_mise_service', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_inscription', models.DateField()),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ligne', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ligne',
                'verbose_name_plural': 'Lignes',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_station', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField()),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.ligne')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'unique_together': {('ligne', 'jour_semaine', 'heure_depart')},
            },
        ),
        migrations.CreateModel(
            name='AffectationEtudiantLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.etudiant')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.ligne')),
            ],
            options={
                'verbose_name': 'Affectation Étudiant-Ligne',
                'verbose_name_plural': 'Affectations Étudiant-Ligne',
            },
        ),
        migrations.CreateModel(
            name='AffectationBusLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.bus')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.ligne')),
            ],
            options={
                'verbose_name': 'Affectation Bus-Ligne',
                'verbose_name_plural': 'Affectations Bus-Ligne',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_trajet', models.DateField()),
                ('retard_minutes', models.PositiveIntegerField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.bus')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.horaire')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.ligne')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_heure_incident', models.DateTimeField()),
                ('type_incident', models.CharField(blank=True, max_length=50)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.trajet')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='LigneStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.ligne')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.station')),
            ],
            options={
                'verbose_name': 'Ligne-Station',
                'verbose_name_plural': 'Lignes-Stations',
                'unique_together': {('ligne', 'station')},
            },
        ),
    ]
