# Generated by Django 6.0.4 on 2026-04-25 09:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='student_number',
            field=models.CharField(default='0000000000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro d'étudiant doit contenir exactement 10 chiffres.", regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
