# Generated by Django 6.0.4 on 2026-04-25 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0002_etudiant_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='student_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro d'étudiant doit contenir exactement 8 chiffres.", regex='^\\d{8}$')]),
        ),
    ]
