# Generated by Django 6.0.4 on 2026-05-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0005_trajet_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.etudiant')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.horaire')),
            ],
            options={
                'verbose_name': 'Réservation Horaire',
                'verbose_name_plural': 'Réservations Horaires',
                'unique_together': {('etudiant', 'horaire')},
            },
        ),
    ]
