# Generated by Django 6.0.4 on 2026-05-04 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0007_enforce_non_overlapping_bus_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='student_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Le matricule étudiant doit contenir exactement 12 chiffres.', regex='^\\d{12}$')]),
        ),
    ]
