# Generated by Django 6.0.4 on 2026-05-04 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0008_etudiant_password_alter_etudiant_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.etudiant')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_transport.trajet')),
            ],
            options={
                'verbose_name': 'Réservation Trajet',
                'verbose_name_plural': 'Réservations Trajets',
                'unique_together': {('etudiant', 'trajet')},
            },
        ),
    ]
