# Generated by Django 6.0.4 on 2026-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0009_reservationtrajet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('systeme', 'Système')], max_length=20)),
                ('objet_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('utilisateur', models.CharField(blank=True, max_length=150)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historique des modifications',
                'ordering': ['-date_action'],
            },
        ),
    ]
