# Generated by Django 6.0.4 on 2026-05-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0012_bus_conducteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationbusligne',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='gestion_transport.conducteur'),
        ),
    ]
