# Generated by Django 6.0.4 on 2026-05-12 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0017_ligne_nom_unique_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetardTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retard_minutes', models.PositiveIntegerField()),
                ('motif', models.TextField(blank=True, null=True)),
                ('utilisateur_declarant', models.CharField(blank=True, help_text='Identité de qui a déclaré le retard', max_length=150)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_declares', to='gestion_transport.conducteur')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards_historique', to='gestion_transport.trajet')),
            ],
            options={
                'verbose_name': 'Retard Trajet',
                'verbose_name_plural': 'Retards Trajets',
                'ordering': ['-date_declaration'],
            },
        ),
    ]
