# Generated by Django 6.0.4 on 2026-05-12 01:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0018_retardtrajet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_generale', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_bus', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_conducteur', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_trajets', to='gestion_transport.bus')),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_trajets', to='gestion_transport.conducteur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_trajets', to='gestion_transport.etudiant')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_etudiants', to='gestion_transport.trajet')),
            ],
            options={
                'verbose_name': 'Avis Trajet',
                'verbose_name_plural': 'Avis Trajets',
                'ordering': ['-date_mise_a_jour'],
                'unique_together': {('etudiant', 'trajet')},
            },
        ),
    ]
