# Generated by Django 6.0.4 on 2026-05-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transport', '0019_avistrajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtrajet',
            name='ticket_code',
            field=models.CharField(blank=True, help_text='Code unique pour le ticket QR', max_length=64, null=True, unique=True),
        ),
    ]
