from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'gestion_transport'

urlpatterns = [
    path('', views.index, name='index'),
    path('administrateur/', views.admin_dashboard, name='admin_interface'),
    path('etudiant/', views.student_interface, name='student_interface'),
    path('etudiant/connexion/', views.student_login, name='student_login'),

    # Multi-page student dashboard
    path('etudiant/tableau-de-bord/', views.student_dashboard, name='student_dashboard'),
    path('etudiant/trajets/', views.student_trips, name='student_trips'),
    path('etudiant/historique/', views.student_history, name='student_history'),
    path('etudiant/abonnement/', views.student_subscription, name='student_subscription'),
    path('etudiant/tickets/', views.student_tickets, name='student_tickets'),
    path('etudiant/notifications/', views.student_notifications, name='student_notifications'),
    path('etudiant/localisation/', views.student_location, name='student_location'),
    path('etudiant/profil/', views.student_profile, name='student_profile'),
    path('etudiant/subscribe/', views.subscribe_to_line, name='subscribe_to_line'),
    path('etudiant/unsubscribe/', views.unsubscribe_from_line, name='unsubscribe_from_line'),
    path('etudiant/subscriptions/', views.get_student_subscriptions, name='get_student_subscriptions'),
    path('etudiant/reserver-trajet/', views.reserve_trajet, name='reserve_trajet'),
    path('etudiant/annuler-reservation-trajet/', views.cancel_reservation_trajet, name='cancel_reservation_trajet'),
    path('etudiant/noter-trajet/', views.rate_trajet, name='rate_trajet'),
    path('conducteur/', views.driver_interface, name='driver_interface'),
    path('conducteur/connexion/', views.driver_login, name='driver_login'),
    path('conducteur/tableau-de-bord/', views.driver_home, name='driver_home'),
    path('conducteur/deconnexion/', views.driver_logout, name='driver_logout'),
    path('conducteur/trajet/retard/', views.driver_set_retard, name='driver_set_retard'),
    path('conducteur/trajet/incident/', views.driver_report_incident, name='driver_report_incident'),
    path('conducteur/trajet/status/', views.driver_update_trajet_status, name='driver_update_trajet_status'),
    path('conducteur/trajet/save-route-distance/', views.driver_save_route_distance, name='driver_save_route_distance'),
    path('inscription/', views.inscription, name='inscription'),

    path('inscription-conducteur/', views.inscription_conducteur, name='inscription_driver'),

    path('verify-student/', views.verify_student, name='verify_student'),
    path('admin-login/', auth_views.LoginView.as_view(template_name='gestion_transport/admin_login.html', extra_context={'generic_page': True}), name='admin_login'),
    path('admin-logout/', auth_views.LogoutView.as_view(next_page='gestion_transport:admin_login'), name='admin_logout'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('gestion/trajets/resync/', views.resync_trajets, name='resync_trajets'),
    path('gestion/lignes/recompute-distances/', views.recompute_lignes_distances, name='recompute_lignes_distances'),
    path('gestion/bus/ajouter/', views.add_bus, name='add_bus'),
    path('gestion/bus/modifier/<int:bus_id>/', views.edit_bus, name='edit_bus'),
    path('gestion/bus/<int:bus_id>/sync-conducteur/', views.sync_bus_driver_assignments, name='sync_bus_driver_assignments'),
    path('gestion/bus/<int:bus_id>/trajets/', views.bus_trajets, name='bus_trajets'),
    path('gestion/trajet/modifier/<int:trajet_id>/', views.edit_trajet, name='edit_trajet'),
    path('gestion/trajet/supprimer/<int:trajet_id>/', views.delete_trajet, name='delete_trajet'),
    path('gestion/bus/supprimer/<int:bus_id>/', views.delete_bus, name='delete_bus'),
    path('gestion/bus/<int:bus_id>/affectation/ajouter/', views.add_affectation_bus, name='add_affectation_bus'),
    path('gestion/affectation/modifier/<int:affectation_id>/', views.edit_affectation, name='edit_affectation'),
    path('gestion/affectation/supprimer/<int:affectation_id>/', views.delete_affectation, name='delete_affectation'),
    path('gestion/ligne/ajouter/', views.add_ligne, name='add_ligne'),
    path('gestion/ligne/modifier/<int:ligne_id>/', views.edit_ligne, name='edit_ligne'),
    path('gestion/ligne/supprimer/<int:ligne_id>/', views.delete_ligne, name='delete_ligne'),
    # path('gestion/bus/affecter/', views.assign_bus_to_ligne, name='assign_bus_to_ligne'),  # Fonction à implémenter
    path('gestion/bus/affecter-masse/', views.bulk_assign_buses, name='bulk_assign_buses'),
    path('etudiants-par-ligne/', views.nombre_etudiants_par_ligne, name='etudiants_par_ligne'),
    path('etudiant/modifier/<int:etudiant_id>/', views.edit_etudiant, name='edit_etudiant'),
    path('etudiant/supprimer/<int:etudiant_id>/', views.delete_etudiant, name='delete_etudiant'),
    path('liste-conducteurs/', views.liste_conducteurs, name='liste_conducteurs'),
    path('conducteur/modifier/<int:conducteur_id>/', views.edit_conducteur, name='edit_conducteur'),
    path('conducteur/supprimer/<int:conducteur_id>/', views.delete_conducteur, name='delete_conducteur'),
    path('remplissage-bus/', views.taux_remplissage_bus, name='remplissage_bus'),
    path('horaires-ligne/', views.horaires_ligne, name='horaires_ligne'),
    path('horaires-ligne/<int:ligne_id>/', views.horaires_ligne, name='horaires_ligne_detail'),
    path('etudiants-sans-abonnement/', views.etudiants_sans_abonnement, name='etudiants_sans_abonnement'),
    path('historique-etudiant/', views.historique_etudiant, name='historique_etudiant'),
    path('historique-etudiant/<int:etudiant_id>/', views.historique_etudiant, name='historique_etudiant_detail'),
    path('historique-modifications/', views.historique_modifications, name='historique_modifications'),
    path('bus-affectes/', views.bus_affectes_ligne_date, name='bus_affectes'),
    path('liste-bus-affectations/', views.liste_bus_affectations, name='liste_bus_affectations'),
    path('liste-lignes/', views.liste_lignes, name='liste_lignes'),
    path('lignes-chargees/', views.lignes_plus_chargees, name='lignes_chargees'),
    path('trajets-programmes/', views.trajets_programmes, name='trajets_programmes'),
    path('trajets-programmes/dispatch-equitable/', views.dispatch_trajets_equitable, name='dispatch_trajets_equitable'),
    path('trajets-retard/', views.trajets_avec_retard, name='trajets_retard'),
    path('liste-stations/', views.liste_stations, name='liste_stations'),
    path('station/geocode/', views.geocode_station_address, name='geocode_station_address'),
    path('station/ajouter/', views.add_station, name='add_station'),
    path('station/modifier/<int:station_id>/', views.edit_station, name='edit_station'),
    path('station/supprimer/<int:station_id>/', views.delete_station, name='delete_station'),
    path('trajets/', views.trajets, name='trajets'),
    path('api/lignes-proches/', views.get_nearby_lines, name='get_nearby_lines'),
]